src/battlehack/core/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns(
    'battlehack.core.views',
    url('^$', 'index', name='index'),
    url(r'^login/$', 'login', name='login'),
    url(r'^logout/$', 'logout', name='logout'),
    url(r'^challenges/$', 'challenge_list', name='challenge_list'),
    url(r'^challenges/(?P<uuid>[\w\-]+)/$', 'challenge_detail', name='challenge_detail'),
    url(r'^create/$', 'challenge_create', name='challenge_create'),
    url(r'^update/(?P<uuid>[\w\-]+)/$', 'attendee_update', name='attendee_update'),
)

src/battlehack/urls.py
from django.conf import settings
from django.conf.urls import include, patterns, url
from django.contrib import admin

from battlehack.utils.views import GenericTemplateView


admin.autodiscover()


urlpatterns = patterns(
    '',
    url(r'^socialauth/', include('social.apps.django_app.urls', namespace='social')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^paypal/', include('battlehack.paypal.urls', namespace='paypal')),
    url(r'^', include('battlehack.core.urls', namespace='core')),
)


if settings.DEBUG:
    urlpatterns += patterns(
        '',
        (r'^test/((?P<template>[\w\-\/]+)/)?$', GenericTemplateView.as_view()),
        (
            r'^%s(?P<path>.*)$' % settings.MEDIA_URL.strip('/'),
            'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}
        ),
    )

templates/modules/navigation/navigation.html
{% if request.user.is_authenticated %}
	<nav class="navigation" role="navigation">
		<ul>
			<li>
				<a href="{% url 'core:challenge_create' %}" title="create a new challenge">
					<i class="fa fa-plus fa-lg"></i>
					<span>New challenge</span>
				</a>
			</li>
			<li>
				<a href="{% url 'core:challenge_list' %}" title="create a new challenge">
					<i class="fa fa-history fa-lg"></i>
					<span>List my challenges</span>
				</a>
			</li>
			<li>
				<a href="{% url 'core:logout' %}" title="create a new challenge">
					<i class="fa fa-power-off fa-lg"></i>
					<span>Logout</span>
				</a>
			</li>
		</ul>
	</nav>
{% endif %}