src/battlehack/core/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns(
    'battlehack.core.views',
    url('^$', 'index', name='index'),
    url(r'^login/$', 'login', name='login'),
    url(r'^logout/$', 'logout', name='logout'),
    url(r'^challenges/$', 'challenge_list', name='challenge_list'),
    url(r'^challenges/(?P<uuid>[\w\-]+)/$', 'challenge_detail', name='challenge_detail'),
    url(r'^create/$', 'challenge_create', name='challenge_create'),
    url(r'^update/(?P<uuid>[\w\-]+)/$', 'attendee_update', name='attendee_update'),
)

src/battlehack/urls.py
from django.conf import settings
from django.conf.urls import include, patterns, url
from django.contrib import admin

from battlehack.utils.views import GenericTemplateView


admin.autodiscover()


urlpatterns = patterns(
    '',
    url(r'^socialauth/', include('social.apps.django_app.urls', namespace='social')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^paypal/', include('battlehack.paypal.urls', namespace='paypal')),
    url(r'^', include('battlehack.core.urls', namespace='core')),
)


if settings.DEBUG:
    urlpatterns += patterns(
        '',
        (r'^test/((?P<template>[\w\-\/]+)/)?$', GenericTemplateView.as_view()),
        (
            r'^%s(?P<path>.*)$' % settings.MEDIA_URL.strip('/'),
            'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}
        ),
    )

templates/base.html
{% load static from staticfiles %}


<!DOCTYPE html>
<!--[if lt IE 7]>	<html class="no-js ie6 oldie msie"> <![endif]-->
<!--[if IE 7]>		<html class="no-js ie7 oldie msie"> <![endif]-->
<!--[if IE 8]>		<html class="no-js ie8 oldie msie"> <![endif]-->
<!--[if IE 9]>		<html class="no-js ie9 msie"> <![endif]-->
<!--[if gt IE 9]><!--> <html itemscope itemtype="http://schema.org/WebPage"> <!--<![endif]-->
	<head>
		<meta charset="utf-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
		<meta http-equiv="content-language" content="{{ LANGUAGE_CODE }}" />
		<meta name="robots" content="noindex, nofollow" />
		<meta name="siteinfo" content="{% static 'robots.txt' %}" />
		<meta name="viewport" content="initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=0,width=device-width" />
		<title>Cha+Cha</title>
		<link href="http://fonts.googleapis.com/css?family=Open+Sans:300,600" rel="stylesheet" type="text/css" />
		<link href="{% static 'css/styles.css' %}" rel="stylesheet" type="text/css" />

		<link rel="apple-touch-icon" href="{% static 'img/apple-touch-57x57.png' %}" sizes="57x57" />
		<link rel="apple-touch-icon" href="{% static 'img/apple-touch-72x72.png' %}" sizes="72x72" />
		<link rel="apple-touch-icon" href="{% static 'img/apple-touch-114x114.png' %}" sizes="114x114" />
		<link rel="apple-touch-icon" href="{% static 'img/apple-touch-144x144.png' %}" sizes="144x144" />
	</head>
	<body>
		<header>
			<h1>
				{% url 'core:login' as url_login %}
				{% url 'core:challenge_list' as url_list %}
				<a href="{% if request.user.is_authenticated %}{{ url_list }}{% else %}{{ url_login }}{% endif %} ">
					Cha<i class="fa fa-plus-square fa-lg"></i>Cha
				</a>
			</h1>
			{% include "modules/navigation/navigation.html" %}
		</header>

		<div class="container">
			{% block content %}
			{% endblock %}
		</div>

		<script type="text/javascript" src="{% static 'js/libs/jquery/jquery.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/libs/uniform/jquery.uniform.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/libs/chart/chart.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/src/modules/stats.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/src/init.js' %}"></script>
	</body>
</html>