src/battlehack/core/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns(
    'battlehack.core.views',
    url('^$', 'index', name='index'),
    url(r'^login/$', 'login', name='login'),
    url(r'^logout/$', 'logout', name='logout'),
    url(r'^challenges/$', 'challenge_list', name='challenge_list'),
    url(r'^challenges/(?P<uuid>[\w\-]+)/$', 'challenge_detail', name='challenge_detail'),
    url(r'^create/$', 'challenge_create', name='challenge_create'),
    url(r'^update/(?P<uuid>[\w\-]+)/$', 'attendee_update', name='attendee_update'),
)

src/battlehack/paypal/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns(
    'battlehack.paypal.views',
    url('^start/(?P<uuid>[\w\-]+)/$', 'start', name='start'),
    url('^success/(?P<uuid>[\w\-]+)/$', 'success', name='success'),
    url('^cancel/(?P<uuid>[\w\-]+)/$', 'cancel', name='cancel'),
)

src/battlehack/urls.py
from django.conf import settings
from django.conf.urls import include, patterns, url
from django.contrib import admin

from battlehack.utils.views import GenericTemplateView


admin.autodiscover()


urlpatterns = patterns(
    '',
    url(r'^socialauth/', include('social.apps.django_app.urls', namespace='social')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^paypal/', include('battlehack.paypal.urls', namespace='paypal')),
    url(r'^', include('battlehack.core.urls', namespace='core')),
)


if settings.DEBUG:
    urlpatterns += patterns(
        '',
        (r'^test/((?P<template>[\w\-\/]+)/)?$', GenericTemplateView.as_view()),
        (
            r'^%s(?P<path>.*)$' % settings.MEDIA_URL.strip('/'),
            'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}
        ),
    )

templates/modules/challenge/detail/confirm.html
<div class="challenge-confirm">
	<p>{{ challenge.owner.user.username }} wants to invite you to a challenge. Do you accept?</p>
	<div class="decision">
		<form method="post" action="{% url 'core:attendee_update' uuid=attendee.uuid %}">
			<button type="submit" name="status" value="refuse" class="no">
				<i class="fa fa-thumbs-down fa-lg"></i>
			</button>
			<a href="{% url 'paypal:start' uuid=attendee.uuid %}" class="yes">
				<i class="fa fa-thumbs-up fa-lg"></i>
			</a>
		</form>
	</div>
</div>

templates/modules/challenge/detail/finished.html
<div class="challenge-finished">
	<h2>The challenge is over!</h2>
	<p>
		{% if challenge.rival.status == challenge.owner.status %}
			<i class="smiley fa fa-frown-o fa-lg"></i>
			Both challengers select the same status, so now your money will
			be donated to <strong>{{ challenge.charity.name }}</strong>. Thank you very much!
		{% elif attendee.status == 'loose' %}
			<i class="smiley fa fa-frown-o fa-lg"></i>
			You lose this challenge, so now your money will be donated to
			<strong>{{ challenge.charity.name }}</strong>. Thank you very much!
		{% else %}
			<i class="smiley fa fa-smile-o fa-lg"></i>
			You won the challenge, so you get your money back. Congratulations!
		{% endif %}
	</p>

	{% if request.user.is_authenticated %}
		<a href="{% url 'core:challenge_list' %}" class="back">
			<span class="fa fa-chevron-left"></span>
			Back to my challenges
		</a>
	{% endif %}
</div>

templates/modules/challenge/detail/waiting-for-confirmation.html
<div class="waiting">
	Thank you for starting a challenge. An email has been sent to your opponent.<br />
	Stay tuned, to win your challenge.
	<a href="{% url 'core:challenge_detail' uuid=attendee.opponent.uuid %}">
		<i class="fa fa-meh-o fa-lg"></i>
	</a>
</div>

templates/modules/challenge/detail/waiting-for-decision.html
<div class="challenge-decision">
	<h2>Did you win the challenge?</h2>
	<div class="decision">
		{% if attendee.status == 'pending' %}
			<form method="post" action="{% url 'core:attendee_update' uuid=attendee.uuid %}">
				{% csrf_token %}
				<button type="submit" name="status" value="loose" class="no">
					<i class="fa fa-thumbs-down fa-lg"></i>
				</button>
				<button type="submit" name="status" value="win" class="yes">
					<i class="fa fa-thumbs-up fa-lg"></i>
				</button>
			</form>
		{% else %}
			<span class="result {{ attendee.status }}">
				<i class="fa fa-{% if attendee.status == 'win' %}thumbs-up{% else %}thumps-down{% endif %} fa-lg"></i>
			</span>
		{% endif %}

		<p>
			{% if attendee.opponent.status == 'pending' %}
				Your opponent has not made a decision yet.
			{% else %}
				{% if attendee.opponent.status == 'win' %}
					Your opponent claims the victory.
				{% else %}
					Your opponent gave up.
				{% endif %}
			{% endif %}
		</p>
	</div>
</div>